[workspace.package]
version = "0.1.0"
edition = "2021"
repository = "https://github.com/NethermindEth/pq-signatures"

[workspace]
members = [
    "labrador",
]
resolver = "2"
default-members = ["labrador"]

[workspace.dependencies]
# None so far
